# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('session_schedule', models.JSONField(default=list, help_text='Array of {time: Timestamp, topic: String}')),
                ('rating', models.IntegerField(blank=True, help_text='Rating 1-5 after completion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mentor_matches',
                'ordering': ['-created_at'],
            },
        ),
    ]
