# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormatch',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_matches', to='users.user'),
        ),
        migrations.AddField(
            model_name='mentormatch',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='mentormatch',
            unique_together={('learner', 'mentor')},
        ),
    ]
