# Generated by Django 4.2.7 on 2025-11-05 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentormatch",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rating 1-5 after completion",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="mentormatch",
            index=models.Index(fields=["status"], name="mentor_matc_status_588093_idx"),
        ),
        migrations.AddIndex(
            model_name="mentormatch",
            index=models.Index(
                fields=["created_at"], name="mentor_matc_created_fc8c5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentormatch",
            index=models.Index(
                fields=["learner", "status"], name="mentor_matc_learner_2ad7fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentormatch",
            index=models.Index(
                fields=["mentor", "status"], name="mentor_matc_mentor__050865_idx"
            ),
        ),
    ]
