# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text="e.g., 'Python', 'Blockchain'", max_length=100)),
                ('modules', models.JSONField(default=list, help_text='Array of {name: String, resources: Array<URL>, estimated_time: Integer, completed: Boolean}')),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['-created_at'],
            },
        ),
    ]
