# Generated by Django 4.2.7 on 2025-11-05 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmaps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmap",
            name="progress",
            field=models.FloatField(
                default=0.0,
                help_text="Progress percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["user", "domain"], name="roadmaps_user_id_16ed21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["progress"], name="roadmaps_progres_dc9bf5_idx"),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["created_at"], name="roadmaps_created_10b8dc_idx"
            ),
        ),
    ]
