# Generated by Django 4.2.7 on 2025-11-05 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumpost",
            options={"ordering": ["-is_pinned", "-last_activity"]},
        ),
        migrations.AddField(
            model_name="forumpost",
            name="downvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Lock post from new replies"
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Pin post to top of category"
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="title",
            field=models.CharField(
                default="Untitled Post",
                help_text="Post title",
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("web-development", "Web Development"),
                    ("data-science", "Data Science"),
                    ("machine-learning", "Machine Learning"),
                    ("mobile-development", "Mobile Development"),
                    ("devops", "DevOps"),
                    ("databases", "Databases"),
                    ("career-advice", "Career Advice"),
                    ("general", "General Discussion"),
                ],
                help_text="Forum category",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="content",
            field=models.TextField(
                help_text="Post content",
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(fields=["user"], name="forum_posts_user_id_8a1540_idx"),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["is_pinned"], name="forum_posts_is_pinn_1d548b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["last_activity"], name="forum_posts_last_ac_ba3de4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["created_at"], name="forum_posts_created_61a79a_idx"
            ),
        ),
    ]
