# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text="e.g., 'Bronze Mentor'", max_length=100)),
                ('criteria', models.JSONField(help_text='e.g., {sessions_completed: Integer}')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
