# Generated by Django 4.2.7 on 2025-11-05 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badges", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="criteria",
            field=models.JSONField(help_text="Criteria met for earning the badge"),
        ),
        migrations.AlterField(
            model_name="badge",
            name="type",
            field=models.CharField(
                choices=[
                    ("First Steps", "First Steps"),
                    ("Mentor", "Mentor"),
                    ("Dedicated Learner", "Dedicated Learner"),
                    ("Code Contributor", "Code Contributor"),
                    ("Community Builder", "Community Builder"),
                    ("Mentor Extraordinaire", "Mentor Extraordinaire"),
                    ("Knowledge Sharer", "Knowledge Sharer"),
                ],
                help_text="Badge type",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="badge",
            unique_together={("mentor", "type")},
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["mentor"], name="badges_mentor__e10434_idx"),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["type"], name="badges_type_bea2e4_idx"),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["awarded_at"], name="badges_awarded_13c1ac_idx"),
        ),
    ]
