# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('commit', 'Commit'), ('pull_request', 'Pull Request'), ('issue', 'Issue'), ('module_complete', 'Module Complete')], max_length=20)),
                ('details', models.JSONField(help_text='e.g., {repo: String, commit_hash: String}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'progress_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
