# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='roadmaps.roadmap'),
        ),
    ]
