# Generated by Django 4.2 on 2025-11-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['user', 'roadmap'], name='progress_lo_user_id_212e75_idx'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['event_type'], name='progress_lo_event_t_eff8a8_idx'),
        ),
    ]
