# Generated by Django 4.2.7 on 2025-11-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roadmaps", "0003_alter_roadmap_progress_and_more"),
        ("progress", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresslog",
            name="details",
            field=models.JSONField(help_text="Event-specific details"),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("commit", "Commit"),
                    ("pull_request", "Pull Request"),
                    ("issue", "Issue"),
                    ("module_complete", "Module Complete"),
                    ("roadmap_created", "Roadmap Created"),
                    ("session_completed", "Session Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="roadmap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_logs",
                to="roadmaps.roadmap",
            ),
        ),
        migrations.AddIndex(
            model_name="progresslog",
            index=models.Index(
                fields=["timestamp"], name="progress_lo_timesta_fd26cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progresslog",
            index=models.Index(
                fields=["user", "event_type"], name="progress_lo_user_id_0679cd_idx"
            ),
        ),
    ]
